function createGrammarLesson(id, kana, name, patterns) {
  return {
    id,
    kana,
    name,
    chars: patterns.map(
      ([k, reading, meaning, exampleJa, exampleJaHiragana, exampleEn, hanaExplanation]) => ({
        k,
        reading,
        r: reading,
        meaning,
        voice: k,
        exampleJa,
        exampleJaHiragana,
        exampleEn,
        hanaExplanation: hanaExplanation || "",
      })
    ),
  };
}

export const grammarLessons = [
  createGrammarLesson(1, "文", "Copula and Basic Statements", [
    ["です", "desu", "is / am / are (polite)", "これは本です。", "これはほんです。", "This is a book.", "です (desu) is the polite way to say 'is' or 'am' in Japanese. You put it at the end of a sentence to make it sound respectful — Japanese grammar works back-to-front compared to English! A common beginner mistake is forgetting です at the end, which makes the sentence sound very casual or even rude."],
    ["じゃありません", "ja arimasen", "is not (polite)", "先生じゃありません。", "せんせいじゃありません。", "I am not a teacher.", "To say something is NOT something, you replace です with じゃありません. Think of it as the polite 'undo' button for です. A natural mistake is saying ですない — that doesn't exist! Always use じゃありません for polite negation."],
    ["ですか", "desu ka", "question ending", "日本人ですか。", "にほんじんですか。", "Are you Japanese?", "Japanese doesn't flip words around to ask questions like English does. You just add か (ka) at the end of a statement and it becomes a question — your voice goes up naturally. No need to rearrange anything, which makes it one of the easiest grammar rules to learn!"],
    ["〜は〜です", "wa ... desu", "A is B", "私は学生です。", "わたしはがくせいです。", "I am a student.", "This is THE core Japanese sentence pattern. は (wa) marks your topic — what you're talking about — and です tells us what it is. Think of は as saying 'as for…' — 'as for me, I am a student.' Note: は is written with the hiragana は but pronounced 'wa' when used as a particle."],
    ["〜も", "mo", "also / too", "田中さんも学生です。", "たなかさんもがくせいです。", "Tanaka is also a student.", "も (mo) simply replaces は when you want to say 'also' or 'too.' If someone says 'I'm a student' and you are too, you swap は for も. Be careful: も replaces は completely — saying はも is a common beginner error!"],
    ["これ / それ / あれ", "kore / sore / are", "this / that / that over there", "これはペンです。", "これはぺんです。", "This is a pen.", "Japanese has three levels of 'this/that' based on distance: これ (near me), それ (near you), and あれ (far from both of us). English only has two (this/that), so あれ is a new concept — think of pointing across a room. This ko-so-a-do pattern shows up everywhere in Japanese!"],
    ["どれ", "dore", "which one", "どれですか。", "どれですか。", "Which one is it?", "どれ is the question word for 'which one' and completes the ko-so-a-do set: これ, それ, あれ, どれ. Use it when there are three or more choices. For only two choices, use どちら instead — it's more polite too!"],
    ["の", "no", "possessive 'of'", "これは私の本です。", "これはわたしのほんです。", "This is my book.", "の (no) connects two nouns and usually shows possession, like 's in English. 私の本 = 'my book', literally 'I の book.' It can also link nouns more broadly — 日本の車 means 'Japan's car' or 'a Japanese car.' Just remember: the owner always comes before の."],
  ]),
  createGrammarLesson(2, "時", "Time and Existence", [
    ["あります", "arimasu", "there is (inanimate)", "机の上に本があります。", "つくえのうえにほんがあります。", "There is a book on the desk.", "あります is used to say something exists — but only for non-living things like books, buildings, or keys. Japanese splits 'there is' into two verbs depending on whether the thing is alive or not. If you use あります for a person, it sounds like you're talking about an object!"],
    ["います", "imasu", "there is (animate)", "教室に先生がいます。", "きょうしつにせんせいがいます。", "There is a teacher in the classroom.", "います is the living version of あります — use it for people, animals, and anything that moves on its own. A fish uses います, but a robot uses あります. This alive-vs-not-alive split is one of the most important distinctions in beginner Japanese."],
    ["〜に", "ni", "at / in / on (location)", "学校にいます。", "がっこうにいます。", "I am at school.", "に (ni) pins down the exact location where something exists. Think of it as a thumbtack on a map — it tells you precisely where. When used with あります or います, に marks where the thing is. Don't confuse it with で, which marks where an action happens!"],
    ["〜で", "de", "at (action place)", "図書館で勉強します。", "としょかんでべんきょうします。", "I study at the library.", "で (de) marks the place where an action takes place — studying, eating, playing. The key difference from に is that で needs a verb of action. You 'exist' に a place, but you 'do things' で a place. Mixing these up is the #1 particle mistake for beginners!"],
    ["〜から", "kara", "from", "九時から勉強します。", "くじからべんきょうします。", "I study from nine o'clock.", "から (kara) means 'from' and marks a starting point — in time or in space. '9時から' means 'from 9 o'clock.' It pairs naturally with まで (until) to show a range. You'll hear から constantly in daily Japanese!"],
    ["〜まで", "made", "until", "五時まで働きます。", "ごじまではたらきます。", "I work until five.", "まで (made) means 'until' or 'up to' and marks an ending point. It pairs perfectly with から to create time ranges: 9時から5時まで = 'from 9 to 5.' まで can also mean 'as far as' for places — 駅まで means 'up to the station.'"],
    ["〜と", "to", "and / with", "友達と行きます。", "ともだちといきます。", "I go with a friend.", "と (to) connects things together — it means 'and' between nouns or 'with' before a verb. Unlike English, you can't use と between sentences, only between nouns. For listing sentences, you'll learn other connectors like そして later!"],
    ["〜や", "ya", "A and B and so on", "りんごやバナナを食べます。", "りんごやばななをたべます。", "I eat apples, bananas, and so on.", "や (ya) is like と but with an implied 'etc.' at the end — it lists examples without being exhaustive. 'りんごやバナナ' means 'apples, bananas, and other things.' Use と when your list is complete, や when it's just a sample."],
  ]),
  createGrammarLesson(3, "動", "Verb Basics (Present / Past)", [
    ["〜ます", "masu", "polite present/future", "毎日日本語を勉強します。", "まいにちにほんごをべんきょうします。", "I study Japanese every day.", "〜ます (masu) is the polite verb ending you'll use in 90% of real conversations. It covers both present and future — Japanese doesn't separate 'I eat' and 'I will eat.' Just attach ます to a verb stem and you're speaking politely!"],
    ["〜ません", "masen", "polite negative", "今日は行きません。", "きょうはいきません。", "I will not go today.", "To say you don't do something, swap ます for ません. It's beautifully simple — no extra words needed. 行きます (I go) → 行きません (I don't go). This covers both present and future negation, just like ます covers both present and future."],
    ["〜ました", "mashita", "polite past", "昨日映画を見ました。", "きのうえいがをみました。", "I watched a movie yesterday.", "ました turns any polite verb into the past tense. Swap ます → ました and you're done. 食べます (I eat) → 食べました (I ate). Unlike English, where past tense is chaotic (eat→ate, go→went), Japanese past tense is perfectly regular!"],
    ["〜ませんでした", "masen deshita", "polite past negative", "朝ごはんを食べませんでした。", "あさごはんをたべませんでした。", "I did not eat breakfast.", "For 'didn't do,' use ませんでした — it's ません (negative) + でした (past). It's a mouthful, but it follows a perfect pattern: ます → ません → ました → ませんでした. Once you see the system, it clicks!"],
    ["行きます", "ikimasu", "to go", "学校へ行きます。", "がっこうへいきます。", "I go to school.", "行きます (ikimasu) is one of the first verbs you'll memorize. The stem is 行き and ます makes it polite. Notice it pairs with へ (direction) — 学校へ行きます means 'I go toward school.' This is a verb you'll use every single day!"],
    ["食べます", "tabemasu", "to eat", "すしを食べます。", "すしをたべます。", "I eat sushi.", "食べます (tabemasu) is an essential daily verb. It's a 'Group 2' verb (ichidan), which means conjugation is super easy — just drop ます and add the new ending. The object you eat gets marked with を: すしを食べます."],
    ["見ます", "mimasu", "to see/watch", "テレビを見ます。", "てれびをみます。", "I watch TV.", "見ます (mimasu) covers both 'see' and 'watch' in Japanese — no need to pick between them. It's another Group 2 verb, so conjugation is easy. Use を to mark what you're watching: テレビを見ます = 'I watch TV.'"],
    ["します", "shimasu", "to do", "宿題をします。", "しゅくだいをします。", "I do homework.", "します (shimasu) means 'to do' and is incredibly versatile. Many activities are formed by adding します to a noun: 勉強します (study), 料理します (cook), 買い物します (shop). It's an irregular verb, but since you'll use it so often, you'll memorize it naturally!"],
  ]),
  createGrammarLesson(4, "形", "Adjectives and Description", [
    ["い-adjective", "i keiyoushi", "adjective ending with い", "この本は面白いです。", "このほんはおもしろいです。", "This book is interesting.", "い-adjectives always end with い and can stand on their own: 面白い = 'interesting.' You can add です for politeness, but the adjective itself carries the meaning. The cool part: い-adjectives conjugate just by changing that い ending — no extra words needed!"],
    ["な-adjective", "na keiyoushi", "adjective requiring な", "この町は静かです。", "このまちはしずかです。", "This town is quiet.", "な-adjectives need な when placed before a noun: 静かな町 = 'quiet town.' But when ending a sentence, they use です just like nouns: 静かです. The tricky part is knowing which adjectives are な-type — きれい (pretty) looks like い-adjective but is actually な-adjective!"],
    ["〜くないです", "kunai desu", "not (i-adjective)", "今日は寒くないです。", "きょうはさむくないです。", "It is not cold today.", "To negate an い-adjective, drop the い and add くない: 寒い → 寒くない (not cold). Add です for politeness: 寒くないです. This is one of those beautiful Japanese patterns — once you learn it, it works for every い-adjective with zero exceptions!"],
    ["〜じゃありません", "ja arimasen", "not (na-adjective)", "ここはにぎやかじゃありません。", "ここはにぎやかじゃありません。", "This place is not lively.", "な-adjectives negate the same way as nouns — just add じゃありません after the adjective. 静かです → 静かじゃありません. Don't try to change the adjective itself like you do with い-adjectives — な-adjectives stay unchanged, and the negation is all in じゃありません."],
    ["〜かったです", "katta desu", "past (i-adjective)", "映画は長かったです。", "えいがはながかったです。", "The movie was long.", "For past tense い-adjectives, drop い and add かった: 長い → 長かった (was long). Add です for politeness. This is fun because the adjective itself changes tense — you don't need a separate past tense verb. One word does it all!"],
    ["〜でした", "deshita", "past (na-adjective/noun)", "駅は便利でした。", "えきはべんりでした。", "The station was convenient.", "For な-adjectives and nouns in the past, replace です with でした. 便利です → 便利でした (was convenient). The adjective doesn't change — only the ending does. This is the same pattern as noun sentences: 学生です → 学生でした."],
    ["とても", "totemo", "very", "とても有名です。", "とてもゆうめいです。", "It is very famous.", "とても goes right before an adjective to mean 'very' — just like English! とても面白い = 'very interesting.' It works with both い and な adjectives. For a slightly more casual version, you'll hear すごく in everyday speech, but とても is perfect for polite conversation."],
    ["あまり〜ない", "amari ... nai", "not very", "あまり暑くないです。", "あまりあつくないです。", "It is not very hot.", "あまり always pairs with a negative ending to mean 'not very' or 'not much.' あまり暑くない = 'not very hot.' A key mistake is using あまり with a positive — あまり暑い doesn't work! Think of あまり as a word that always needs ない nearby."],
  ]),
  createGrammarLesson(5, "助", "Particles Core Set", [
    ["は", "wa", "topic marker", "私は日本語を勉強します。", "わたしはにほんごをべんきょうします。", "As for me, I study Japanese.", "は (wa) marks the topic of your sentence — the thing you're talking about. Think of it as saying 'as for…' or 'speaking of…' It doesn't mean 'is' by itself — it just points a spotlight at one word. Fun fact: it's written with the hiragana は but pronounced 'wa' only as a particle!"],
    ["が", "ga", "subject marker", "猫が好きです。", "ねこがすきです。", "I like cats.", "が (ga) marks the subject — the thing doing the action or being described. The は vs が distinction is the most famously tricky part of Japanese. A simple rule: use が when introducing new information or with words like 好き and ほしい. You'll develop a feel for it over time!"],
    ["を", "wo", "object marker", "水を飲みます。", "みずをのみます。", "I drink water.", "を (wo) marks the direct object — the thing being acted upon. 水を飲みます = 'drink water,' where water is what's being drunk. を is pronounced 'o' in modern Japanese, not 'wo.' It's one of the simplest particles: just place it right after whatever the verb is acting on."],
    ["に", "ni", "time/destination marker", "七時に起きます。", "しちじにおきます。", "I wake up at seven.", "に (ni) is the Swiss Army knife of particles — it marks time ('at 7'), destination ('to school'), and location of existence ('at home'). For time, attach に to specific times: 七時に, 月曜日に. But don't use に with relative time like 今日 or 明日 — they don't need it!"],
    ["へ", "e", "direction marker", "日本へ行きます。", "にほんへいきます。", "I go to Japan.", "へ (e) points toward a destination or direction. It's written with へ but pronounced 'e' as a particle. The difference from に? へ emphasizes the direction of travel, while に emphasizes the arrival point. In practice, they're often interchangeable with movement verbs."],
    ["で", "de", "place of action", "家で食べます。", "いえでたべます。", "I eat at home.", "で (de) marks where an action happens — eating, studying, playing. The key rule: に is for existence (being somewhere), で is for activity (doing something somewhere). 家にいます = 'I am at home' but 家で食べます = 'I eat at home.' Action vs existence!"],
    ["と", "to", "with / and", "友達と話します。", "ともだちとはなします。", "I talk with my friend.", "と (to) means 'with' or 'and' and connects nouns together. 友達と = 'with a friend.' When listing items, と gives a complete, closed list: りんごとバナナ = 'apples and bananas (and nothing else).' For an open-ended list, use や instead."],
    ["も", "mo", "also", "私も行きます。", "わたしもいきます。", "I will go too.", "も (mo) means 'also' or 'too' and replaces は or が — it doesn't stack on top of them. 私は行きます → 私も行きます means 'I will go too.' You can even use も multiple times: AもBも = 'both A and B.' It's wonderfully simple!"],
  ]),
  createGrammarLesson(6, "願", "Requests and Permission", [
    ["〜てください", "te kudasai", "please do", "もう一度言ってください。", "もういちどいってください。", "Please say it once more.", "〜てください is the go-to way to politely ask someone to do something. It uses the て-form of a verb + ください (please). This is one of the most useful phrases for daily life — ordering food, asking for directions, or requesting help. You'll sound polite and natural every time!"],
    ["〜てもいいです", "te mo ii desu", "may do / it's okay to", "ここで写真を撮ってもいいです。", "ここでしゃしんをとってもいいです。", "May I take photos here?", "This pattern literally means 'even if you do it, it's good' — which is Japanese for 'you may.' Use the て-form + もいいです to ask permission or give it. To ask politely, add か: 〜てもいいですか？Common in shops, schools, and anywhere you need to check first!"],
    ["〜てはいけません", "te wa ikemasen", "must not", "ここでタバコを吸ってはいけません。", "ここでたばこをすってはいけません。", "You must not smoke here.", "This is the opposite of てもいいです — it means 'you must not do this.' Literally: 'if you do it, it won't do.' You'll see it on signs and hear it from teachers. It's firm but polite — stronger than saying だめ but still proper Japanese."],
    ["〜ましょう", "mashou", "let's", "一緒に勉強しましょう。", "いっしょにべんきょうしましょう。", "Let's study together.", "ましょう replaces ます when you want to suggest doing something together — 'let's!' 食べます → 食べましょう = 'let's eat!' It's warm and inviting. You can also use it as a soft offer: 手伝いましょうか = 'shall I help?' Very useful in group situations!"],
    ["〜ませんか", "masen ka", "won't you?", "映画を見ませんか。", "えいがをみませんか。", "Would you like to watch a movie?", "ませんか is a polite invitation — literally 'won't you…?' It's softer and more considerate than ましょう because you're giving the other person room to decline. 映画を見ませんか sounds like a gentle proposal, not a command. Perfect for inviting friends or colleagues!"],
    ["お願いします", "onegaishimasu", "please (request)", "水をお願いします。", "みずをおねがいします。", "Water, please.", "お願いします is one of the most useful phrases in all of Japanese. It means 'please' when requesting something — at restaurants, shops, or offices. It's more versatile than ください because you can use it with nouns directly: 水をお願いします = 'water, please.' Learn this one early!"],
    ["だめです", "dame desu", "not allowed / no good", "ここはだめです。", "ここはだめです。", "You can't do that here.", "だめ means 'no good' or 'not allowed' and is a direct way to refuse or prohibit something. It's more casual than てはいけません but still clear. Parents often say だめ! to children. Adding です makes it polite. It's short, punchy, and unmistakable."],
    ["いいです", "ii desu", "that's fine / okay", "それでいいです。", "それでいいです。", "That is fine.", "いいです has two opposite meanings depending on context! With rising intonation or after てもいい, it means 'it's fine/okay.' But when declining an offer, いいです means 'no thanks.' Context and tone tell you which meaning is intended — this catches many beginners off guard!"],
  ]),
  createGrammarLesson(7, "比", "Comparisons and Preference", [
    ["〜より", "yori", "than", "電車はバスより速いです。", "でんしゃはばすよりはやいです。", "Trains are faster than buses.", "より (yori) means 'than' and comes after the thing being compared against. 'バスより速い' = 'faster than a bus.' Notice the order is opposite to English — the loser comes first with より, then the winner. Japanese comparisons put the standard first, the result second!"],
    ["〜のほうが", "no hou ga", "A is more...", "日本語のほうが難しいです。", "にほんごのほうがむずかしいです。", "Japanese is harder.", "のほうが puts emphasis on the winner of the comparison — the one that is 'more' of something. 日本語のほうが難しい = 'Japanese is the harder one.' It pairs naturally with より: AよりBのほうが = 'B is more… than A.' Together they make comparisons super clear!"],
    ["どちら", "dochira", "which (of two)", "どちらが安いですか。", "どちらがやすいですか。", "Which is cheaper?", "どちら is the polite way to ask 'which of two options.' It's more formal than どっち, which means the same thing casually. Use it in comparisons: どちらが好きですか = 'which do you prefer?' For three or more options, switch to どれ instead."],
    ["一番", "ichiban", "the most", "これが一番好きです。", "これがいちばんすきです。", "I like this one the most.", "一番 (ichiban) literally means 'number one' and turns any adjective into a superlative — the most, the best, the biggest. これが一番好き = 'I like this the most.' It goes right before the adjective. You'll hear 一番 everywhere, from food recommendations to sports rankings!"],
    ["好きです", "suki desu", "to like", "音楽が好きです。", "おんがくがすきです。", "I like music.", "好き (suki) means 'like' but works as an adjective, not a verb — that's why the thing you like uses が, not を. 猫が好き = 'cats are liked (by me)' rather than 'I like cats.' This が-with-好き pattern is one of the most common beginner mistakes to watch for!"],
    ["嫌いです", "kirai desu", "to dislike", "辛い食べ物が嫌いです。", "からいたべものがきらいです。", "I dislike spicy food.", "嫌い (kirai) is the opposite of 好き and follows the same grammar — the thing you dislike uses が. Be careful with 嫌い in real life though — it's quite direct. Japanese people often soften it by saying ちょっと苦手 (a little weak with) instead of 嫌い to avoid sounding harsh."],
    ["上手です", "jouzu desu", "good at", "田中さんは歌が上手です。", "たなかさんはうたがじょうずです。", "Tanaka is good at singing.", "上手 (jouzu) means 'skilled' or 'good at' and uses が to mark the skill: 歌が上手 = 'good at singing.' Important cultural note: don't use 上手 about yourself — it sounds arrogant! For yourself, use 得意 (tokui) instead. Use 上手 to compliment others."],
    ["下手です", "heta desu", "poor at", "私は料理が下手です。", "わたしはりょうりがへたです。", "I am bad at cooking.", "下手 (heta) is the opposite of 上手 — 'poor at' or 'unskilled.' Unlike 上手, you CAN use 下手 about yourself as a humble expression. But be careful using it about others — saying 'you are 下手' can be very rude! For others, soften it: ちょっと苦手みたいですね."],
  ]),
  createGrammarLesson(8, "連", "Connecting Sentences", [
    ["そして", "soshite", "and then", "朝ごはんを食べます。そして学校へ行きます。", "あさごはんをたべます。そしてがっこうへいきます。", "I eat breakfast, and then I go to school.", "そして connects two sentences in time order — 'and then.' It goes at the start of the second sentence, like a bridge. Eat breakfast. そして、go to school. It's the simplest sentence connector and perfect for telling stories or describing your daily routine in order!"],
    ["でも", "demo", "but", "日本語は難しいです。でも面白いです。", "にほんごはむずかしいです。でもおもしろいです。", "Japanese is difficult, but interesting.", "でも means 'but' or 'however' and starts a new sentence that contrasts with the previous one. It's casual and natural — perfect for conversation. For a more formal version, use しかし. でも is one of those words you'll use constantly once you start forming longer thoughts!"],
    ["だから", "dakara", "so / therefore", "雨です。だから家にいます。", "あめです。だからいえにいます。", "It is raining, so I stay home.", "だから means 'so' or 'therefore' — it shows cause and effect between two sentences. The cause comes first, then だから, then the result. It's logical and clean. Note: だから can sound assertive, so in very polite situations, use ですから instead."],
    ["それから", "sorekara", "after that", "駅へ行きます。それから買い物します。", "えきへいきます。それからかいものします。", "I go to the station, and after that I shop.", "それから means 'after that' or 'and then' — similar to そして but with more emphasis on sequence. Use it when listing things you did one after another. It's great for giving directions too: まっすぐ行きます。それから右に曲がります (go straight, then turn right)."],
    ["〜ので", "node", "because", "疲れたので寝ます。", "つかれたのでねます。", "I am tired, so I will sleep.", "ので connects a reason to a result within the same sentence — smoother than だから. It attaches directly to the reason: 疲れたので寝ます = 'because I'm tired, I'll sleep.' ので sounds softer and more polite than から, making it better for formal situations and explanations."],
    ["〜から", "kara", "because", "時間がないから急ぎます。", "じかんがないからいそぎます。", "Because I have no time, I hurry.", "から as a sentence connector means 'because' (different from the 'from' meaning!). It attaches to the reason: 時間がないから = 'because there's no time.' It's more direct and assertive than ので. In casual speech, から is more common; in polite or work settings, ので is preferred."],
    ["〜たり〜たりします", "tari ... tari shimasu", "do things like A and B", "土曜日は映画を見たり本を読んだりします。", "どようびはえいがをみたりほんをよんだりします。", "On Saturdays, I do things like watching movies and reading books.", "This pattern lists activities as examples — 'things like A and B.' Use the た-form of verbs + り, and end with します. It implies you do other things too, not just what you listed. It's the verb equivalent of the や particle for nouns!"],
    ["〜し", "shi", "and / besides", "この店は安いし、おいしいです。", "このみせはやすいし、おいしいです。", "This shop is cheap and tasty.", "し lists multiple reasons or qualities — 'and besides' or 'and also.' 安いし、おいしい = 'it's cheap AND tasty.' Unlike と, し works with adjectives and sentences, not just nouns. It has a soft 'there are many reasons' feeling that makes your argument sound well-rounded."],
  ]),
];

export const totalGrammarPatterns = grammarLessons.reduce(
  (total, lesson) => total + lesson.chars.length,
  0
);

export function getDailyGrammarLesson() {
  const day = new Date().getDate();
  return grammarLessons[(day - 1) % grammarLessons.length];
}
