const exampleBuilders = [
  ({ k, reading, meaning }) => ({
    exampleJa: `きょうは「${k}」を勉強します。`,
    exampleJaHiragana: `きょうは「${reading}」をべんきょうします。`,
    exampleEn: `Today I am studying the word "${meaning}."`,
  }),
  ({ k, reading, meaning }) => ({
    exampleJa: `先生は「${k}」をもう一度言いました。`,
    exampleJaHiragana: `せんせいは「${reading}」をもういちどいいました。`,
    exampleEn: `The teacher said "${meaning}" one more time.`,
  }),
  ({ k, reading, meaning }) => ({
    exampleJa: `会話で「${k}」を使ってみましょう。`,
    exampleJaHiragana: `かいわで「${reading}」をつかってみましょう。`,
    exampleEn: `Let's try using "${meaning}" in conversation.`,
  }),
  ({ k, reading, meaning }) => ({
    exampleJa: `ノートに「${k}」を書きました。`,
    exampleJaHiragana: `のーとに「${reading}」をかきました。`,
    exampleEn: `I wrote "${meaning}" in my notebook.`,
  }),
  ({ k, reading, meaning }) => ({
    exampleJa: `友達と「${k}」について話しました。`,
    exampleJaHiragana: `ともだちと「${reading}」についてはなしました。`,
    exampleEn: `I talked with a friend about "${meaning}."`,
  }),
];

function buildExamples(word, lessonId, index) {
  const builder = exampleBuilders[(lessonId + index) % exampleBuilders.length];
  return builder(word);
}

function createLesson(id, kana, name, words) {
  return {
    id,
    kana,
    name,
    chars: words.map(([k, reading, r, meaning], index) => ({
      k,
      reading,
      r,
      meaning,
      voice: reading || k,
      ...buildExamples({ k, reading, meaning }, id, index),
    })),
  };
}

export const vocabularyLessons = [
  createLesson(1, "言", "Greetings & Basics", [
    ["こんにちは", "こんにちは", "konnichiwa", "hello"],
    ["おはよう", "おはよう", "ohayou", "good morning"],
    ["こんばんは", "こんばんは", "konbanwa", "good evening"],
    ["さようなら", "さようなら", "sayounara", "goodbye"],
    ["ありがとう", "ありがとう", "arigatou", "thank you"],
    ["すみません", "すみません", "sumimasen", "excuse me / sorry"],
    ["はい", "はい", "hai", "yes"],
    ["いいえ", "いいえ", "iie", "no"],
    ["お願いします", "おねがいします", "onegaishimasu", "please"],
    ["大丈夫", "だいじょうぶ", "daijoubu", "okay / all right"],
    ["私", "わたし", "watashi", "I / me"],
    ["あなた", "あなた", "anata", "you"],
    ["名前", "なまえ", "namae", "name"],
    ["日本", "にほん", "nihon", "Japan"],
    ["英語", "えいご", "eigo", "English language"],
    ["日本語", "にほんご", "nihongo", "Japanese language"],
    ["学生", "がくせい", "gakusei", "student"],
    ["先生", "せんせい", "sensei", "teacher"],
    ["友達", "ともだち", "tomodachi", "friend"],
    ["人", "ひと", "hito", "person"],
  ]),
  createLesson(2, "家", "Family & People", [
    ["家族", "かぞく", "kazoku", "family"],
    ["父", "ちち", "chichi", "father"],
    ["母", "はは", "haha", "mother"],
    ["両親", "りょうしん", "ryoushin", "parents"],
    ["兄", "あに", "ani", "older brother"],
    ["姉", "あね", "ane", "older sister"],
    ["弟", "おとうと", "otouto", "younger brother"],
    ["妹", "いもうと", "imouto", "younger sister"],
    ["祖父", "そふ", "sofu", "grandfather"],
    ["祖母", "そぼ", "sobo", "grandmother"],
    ["子ども", "こども", "kodomo", "child"],
    ["夫", "おっと", "otto", "husband"],
    ["妻", "つま", "tsuma", "wife"],
    ["彼", "かれ", "kare", "he / boyfriend"],
    ["彼女", "かのじょ", "kanojo", "she / girlfriend"],
    ["男", "おとこ", "otoko", "man"],
    ["女", "おんな", "onna", "woman"],
    ["赤ちゃん", "あかちゃん", "akachan", "baby"],
    ["みんな", "みんな", "minna", "everyone"],
    ["一人", "ひとり", "hitori", "one person / alone"],
  ]),
  createLesson(3, "数", "Numbers & Time", [
    ["一", "いち", "ichi", "one"],
    ["二", "に", "ni", "two"],
    ["三", "さん", "san", "three"],
    ["四", "よん", "yon", "four"],
    ["五", "ご", "go", "five"],
    ["六", "ろく", "roku", "six"],
    ["七", "なな", "nana", "seven"],
    ["八", "はち", "hachi", "eight"],
    ["九", "きゅう", "kyuu", "nine"],
    ["十", "じゅう", "juu", "ten"],
    ["今日", "きょう", "kyou", "today"],
    ["明日", "あした", "ashita", "tomorrow"],
    ["昨日", "きのう", "kinou", "yesterday"],
    ["今", "いま", "ima", "now"],
    ["朝", "あさ", "asa", "morning"],
    ["昼", "ひる", "hiru", "noon"],
    ["夜", "よる", "yoru", "night"],
    ["毎日", "まいにち", "mainichi", "every day"],
    ["時間", "じかん", "jikan", "time / hour"],
    ["分", "ふん", "fun", "minute"],
  ]),
  createLesson(4, "日", "Calendar & Dates", [
    ["月曜日", "げつようび", "getsuyoubi", "Monday"],
    ["火曜日", "かようび", "kayoubi", "Tuesday"],
    ["水曜日", "すいようび", "suiyoubi", "Wednesday"],
    ["木曜日", "もくようび", "mokuyoubi", "Thursday"],
    ["金曜日", "きんようび", "kinyoubi", "Friday"],
    ["土曜日", "どようび", "doyoubi", "Saturday"],
    ["日曜日", "にちようび", "nichiyoubi", "Sunday"],
    ["一月", "いちがつ", "ichigatsu", "January"],
    ["二月", "にがつ", "nigatsu", "February"],
    ["三月", "さんがつ", "sangatsu", "March"],
    ["四月", "しがつ", "shigatsu", "April"],
    ["五月", "ごがつ", "gogatsu", "May"],
    ["六月", "ろくがつ", "rokugatsu", "June"],
    ["七月", "しちがつ", "shichigatsu", "July"],
    ["八月", "はちがつ", "hachigatsu", "August"],
    ["九月", "くがつ", "kugatsu", "September"],
    ["十月", "じゅうがつ", "juugatsu", "October"],
    ["十一月", "じゅういちがつ", "juuichigatsu", "November"],
    ["十二月", "じゅうにがつ", "juunigatsu", "December"],
    ["誕生日", "たんじょうび", "tanjoubi", "birthday"],
  ]),
  createLesson(5, "室", "Home & Rooms", [
    ["家", "いえ", "ie", "house"],
    ["部屋", "へや", "heya", "room"],
    ["台所", "だいどころ", "daidokoro", "kitchen"],
    ["お風呂", "おふろ", "ofuro", "bath"],
    ["トイレ", "といれ", "toire", "toilet"],
    ["ドア", "どあ", "doa", "door"],
    ["窓", "まど", "mado", "window"],
    ["机", "つくえ", "tsukue", "desk"],
    ["椅子", "いす", "isu", "chair"],
    ["ベッド", "べっど", "beddo", "bed"],
    ["本棚", "ほんだな", "hondana", "bookshelf"],
    ["電気", "でんき", "denki", "electric light"],
    ["鍵", "かぎ", "kagi", "key"],
    ["玄関", "げんかん", "genkan", "entryway"],
    ["庭", "にわ", "niwa", "garden"],
    ["階段", "かいだん", "kaidan", "stairs"],
    ["住所", "じゅうしょ", "juusho", "address"],
    ["町", "まち", "machi", "town"],
    ["隣", "となり", "tonari", "next door"],
    ["建物", "たてもの", "tatemono", "building"],
  ]),
  createLesson(6, "学", "School & Study", [
    ["学校", "がっこう", "gakkou", "school"],
    ["教室", "きょうしつ", "kyoushitsu", "classroom"],
    ["本", "ほん", "hon", "book"],
    ["ノート", "のーと", "nooto", "notebook"],
    ["鉛筆", "えんぴつ", "enpitsu", "pencil"],
    ["ペン", "ぺん", "pen", "pen"],
    ["消しゴム", "けしごむ", "keshigomu", "eraser"],
    ["かばん", "かばん", "kaban", "bag"],
    ["宿題", "しゅくだい", "shukudai", "homework"],
    ["テスト", "てすと", "tesuto", "test"],
    ["質問", "しつもん", "shitsumon", "question"],
    ["答え", "こたえ", "kotae", "answer"],
    ["勉強", "べんきょう", "benkyou", "study"],
    ["練習", "れんしゅう", "renshuu", "practice"],
    ["授業", "じゅぎょう", "jugyou", "class lesson"],
    ["黒板", "こくばん", "kokuban", "blackboard"],
    ["辞書", "じしょ", "jisho", "dictionary"],
    ["文字", "もじ", "moji", "letter / character"],
    ["漢字", "かんじ", "kanji", "kanji"],
    ["図書館", "としょかん", "toshokan", "library"],
  ]),
  createLesson(7, "食", "Food & Drinks I", [
    ["ご飯", "ごはん", "gohan", "rice / meal"],
    ["パン", "ぱん", "pan", "bread"],
    ["水", "みず", "mizu", "water"],
    ["お茶", "おちゃ", "ocha", "tea"],
    ["牛乳", "ぎゅうにゅう", "gyuunyuu", "milk"],
    ["コーヒー", "こーひー", "koohii", "coffee"],
    ["ジュース", "じゅーす", "juusu", "juice"],
    ["魚", "さかな", "sakana", "fish"],
    ["肉", "にく", "niku", "meat"],
    ["卵", "たまご", "tamago", "egg"],
    ["野菜", "やさい", "yasai", "vegetables"],
    ["果物", "くだもの", "kudamono", "fruit"],
    ["りんご", "りんご", "ringo", "apple"],
    ["みかん", "みかん", "mikan", "mandarin orange"],
    ["バナナ", "ばなな", "banana", "banana"],
    ["朝ご飯", "あさごはん", "asagohan", "breakfast"],
    ["昼ご飯", "ひるごはん", "hirugohan", "lunch"],
    ["晩ご飯", "ばんごはん", "bangohan", "dinner"],
    ["料理", "りょうり", "ryouri", "cooking / dish"],
    ["お腹", "おなか", "onaka", "stomach / belly"],
  ]),
  createLesson(8, "味", "Food & Drinks II", [
    ["店", "みせ", "mise", "shop"],
    ["レストラン", "れすとらん", "resutoran", "restaurant"],
    ["メニュー", "めにゅー", "menyuu", "menu"],
    ["注文", "ちゅうもん", "chuumon", "order"],
    ["皿", "さら", "sara", "plate"],
    ["箸", "はし", "hashi", "chopsticks"],
    ["スプーン", "すぷーん", "supuun", "spoon"],
    ["フォーク", "ふぉーく", "fooku", "fork"],
    ["ナイフ", "ないふ", "naifu", "knife"],
    ["塩", "しお", "shio", "salt"],
    ["砂糖", "さとう", "satou", "sugar"],
    ["醤油", "しょうゆ", "shouyu", "soy sauce"],
    ["味", "あじ", "aji", "taste"],
    ["甘い", "あまい", "amai", "sweet"],
    ["辛い", "からい", "karai", "spicy"],
    ["熱い", "あつい", "atsui", "hot"],
    ["冷たい", "つめたい", "tsumetai", "cold"],
    ["美味しい", "おいしい", "oishii", "delicious"],
    ["飲み物", "のみもの", "nomimono", "drink"],
    ["食べ物", "たべもの", "tabemono", "food"],
  ]),
  createLesson(9, "車", "Transportation", [
    ["車", "くるま", "kuruma", "car"],
    ["電車", "でんしゃ", "densha", "train"],
    ["バス", "ばす", "basu", "bus"],
    ["自転車", "じてんしゃ", "jitensha", "bicycle"],
    ["駅", "えき", "eki", "station"],
    ["空港", "くうこう", "kuukou", "airport"],
    ["飛行機", "ひこうき", "hikouki", "airplane"],
    ["船", "ふね", "fune", "ship"],
    ["タクシー", "たくしー", "takushii", "taxi"],
    ["道", "みち", "michi", "road"],
    ["地図", "ちず", "chizu", "map"],
    ["切符", "きっぷ", "kippu", "ticket"],
    ["入口", "いりぐち", "iriguchi", "entrance"],
    ["出口", "でぐち", "deguchi", "exit"],
    ["左", "ひだり", "hidari", "left"],
    ["右", "みぎ", "migi", "right"],
    ["まっすぐ", "まっすぐ", "massugu", "straight ahead"],
    ["止まる", "とまる", "tomaru", "to stop"],
    ["乗る", "のる", "noru", "to ride"],
    ["降りる", "おりる", "oriru", "to get off"],
  ]),
  createLesson(10, "町", "City & Places", [
    ["スーパー", "すーぱー", "suupaa", "supermarket"],
    ["病院", "びょういん", "byouin", "hospital"],
    ["銀行", "ぎんこう", "ginkou", "bank"],
    ["郵便局", "ゆうびんきょく", "yuubinkyoku", "post office"],
    ["公園", "こうえん", "kouen", "park"],
    ["会社", "かいしゃ", "kaisha", "company"],
    ["駅前", "えきまえ", "ekimae", "in front of the station"],
    ["交番", "こうばん", "kouban", "police box"],
    ["ホテル", "ほてる", "hoteru", "hotel"],
    ["海", "うみ", "umi", "sea"],
    ["山", "やま", "yama", "mountain"],
    ["川", "かわ", "kawa", "river"],
    ["国", "くに", "kuni", "country"],
    ["村", "むら", "mura", "village"],
    ["市", "し", "shi", "city"],
    ["近く", "ちかく", "chikaku", "near"],
    ["遠く", "とおく", "tooku", "far"],
    ["場所", "ばしょ", "basho", "place"],
    ["橋", "はし", "hashi", "bridge"],
    ["角", "かど", "kado", "corner"],
  ]),
  createLesson(11, "体", "Body & Health", [
    ["頭", "あたま", "atama", "head"],
    ["顔", "かお", "kao", "face"],
    ["目", "め", "me", "eye"],
    ["耳", "みみ", "mimi", "ear"],
    ["口", "くち", "kuchi", "mouth"],
    ["手", "て", "te", "hand"],
    ["足", "あし", "ashi", "foot / leg"],
    ["体", "からだ", "karada", "body"],
    ["心", "こころ", "kokoro", "heart / mind"],
    ["病気", "びょうき", "byouki", "illness"],
    ["薬", "くすり", "kusuri", "medicine"],
    ["医者", "いしゃ", "isha", "doctor"],
    ["歯", "は", "ha", "tooth"],
    ["鼻", "はな", "hana", "nose"],
    ["元気", "げんき", "genki", "healthy / energetic"],
    ["痛い", "いたい", "itai", "painful"],
    ["熱", "ねつ", "netsu", "fever"],
    ["風邪", "かぜ", "kaze", "cold / flu"],
    ["看護師", "かんごし", "kangoshi", "nurse"],
    ["休み", "やすみ", "yasumi", "rest / holiday"],
  ]),
  createLesson(12, "天", "Weather & Nature", [
    ["天気", "てんき", "tenki", "weather"],
    ["晴れ", "はれ", "hare", "sunny weather"],
    ["雨", "あめ", "ame", "rain"],
    ["雪", "ゆき", "yuki", "snow"],
    ["風", "かぜ", "kaze", "wind"],
    ["曇り", "くもり", "kumori", "cloudy weather"],
    ["暑い", "あつい", "atsui", "hot weather"],
    ["寒い", "さむい", "samui", "cold weather"],
    ["春", "はる", "haru", "spring"],
    ["夏", "なつ", "natsu", "summer"],
    ["秋", "あき", "aki", "autumn"],
    ["冬", "ふゆ", "fuyu", "winter"],
    ["空", "そら", "sora", "sky"],
    ["星", "ほし", "hoshi", "star"],
    ["太陽", "たいよう", "taiyou", "sun"],
    ["月", "つき", "tsuki", "moon"],
    ["花", "はな", "hana", "flower"],
    ["木", "き", "ki", "tree"],
    ["草", "くさ", "kusa", "grass"],
    ["雲", "くも", "kumo", "cloud"],
  ]),
  createLesson(13, "買", "Shopping & Money", [
    ["買い物", "かいもの", "kaimono", "shopping"],
    ["お金", "おかね", "okane", "money"],
    ["円", "えん", "en", "yen"],
    ["財布", "さいふ", "saifu", "wallet"],
    ["値段", "ねだん", "nedan", "price"],
    ["安い", "やすい", "yasui", "cheap"],
    ["高い", "たかい", "takai", "expensive / high"],
    ["売る", "うる", "uru", "to sell"],
    ["買う", "かう", "kau", "to buy"],
    ["店員", "てんいん", "tenin", "store clerk"],
    ["お客", "おきゃく", "okyaku", "customer"],
    ["シャツ", "しゃつ", "shatsu", "shirt"],
    ["靴", "くつ", "kutsu", "shoes"],
    ["帽子", "ぼうし", "boushi", "hat"],
    ["服", "ふく", "fuku", "clothes"],
    ["色", "いろ", "iro", "color"],
    ["サイズ", "さいず", "saizu", "size"],
    ["新しい", "あたらしい", "atarashii", "new"],
    ["古い", "ふるい", "furui", "old"],
    ["必要", "ひつよう", "hitsuyou", "necessary"],
  ]),
  createLesson(14, "仕", "Work & Office", [
    ["仕事", "しごと", "shigoto", "work"],
    ["会社", "かいしゃ", "kaisha", "company"],
    ["社員", "しゃいん", "shain", "employee"],
    ["会議", "かいぎ", "kaigi", "meeting"],
    ["電話", "でんわ", "denwa", "telephone"],
    ["メール", "めーる", "meeru", "email"],
    ["パソコン", "ぱそこん", "pasokon", "computer"],
    ["紙", "かみ", "kami", "paper"],
    ["書類", "しょるい", "shorui", "documents"],
    ["予定", "よてい", "yotei", "schedule"],
    ["忙しい", "いそがしい", "isogashii", "busy"],
    ["簡単", "かんたん", "kantan", "easy / simple"],
    ["難しい", "むずかしい", "muzukashii", "difficult"],
    ["作る", "つくる", "tsukuru", "to make"],
    ["使う", "つかう", "tsukau", "to use"],
    ["働く", "はたらく", "hataraku", "to work"],
    ["終わる", "おわる", "owaru", "to finish"],
    ["始まる", "はじまる", "hajimaru", "to begin"],
    ["手伝う", "てつだう", "tetsudau", "to help"],
    ["送る", "おくる", "okuru", "to send"],
  ]),
  createLesson(15, "動", "Daily Verbs I", [
    ["行く", "いく", "iku", "to go"],
    ["来る", "くる", "kuru", "to come"],
    ["帰る", "かえる", "kaeru", "to return"],
    ["見る", "みる", "miru", "to see"],
    ["聞く", "きく", "kiku", "to listen / ask"],
    ["話す", "はなす", "hanasu", "to speak"],
    ["読む", "よむ", "yomu", "to read"],
    ["書く", "かく", "kaku", "to write"],
    ["食べる", "たべる", "taberu", "to eat"],
    ["飲む", "のむ", "nomu", "to drink"],
    ["起きる", "おきる", "okiru", "to wake up"],
    ["寝る", "ねる", "neru", "to sleep"],
    ["会う", "あう", "au", "to meet"],
    ["待つ", "まつ", "matsu", "to wait"],
    ["立つ", "たつ", "tatsu", "to stand"],
    ["座る", "すわる", "suwaru", "to sit"],
    ["歩く", "あるく", "aruku", "to walk"],
    ["走る", "はしる", "hashiru", "to run"],
    ["入る", "はいる", "hairu", "to enter"],
    ["出る", "でる", "deru", "to leave"],
  ]),
  createLesson(16, "活", "Daily Verbs II", [
    ["する", "する", "suru", "to do"],
    ["ある", "ある", "aru", "to exist (inanimate)"],
    ["いる", "いる", "iru", "to exist (animate)"],
    ["開ける", "あける", "akeru", "to open"],
    ["閉める", "しめる", "shimeru", "to close"],
    ["教える", "おしえる", "oshieru", "to teach"],
    ["習う", "ならう", "narau", "to learn"],
    ["借りる", "かりる", "kariru", "to borrow"],
    ["貸す", "かす", "kasu", "to lend"],
    ["もらう", "もらう", "morau", "to receive"],
    ["あげる", "あげる", "ageru", "to give"],
    ["洗う", "あらう", "arau", "to wash"],
    ["切る", "きる", "kiru", "to cut"],
    ["持つ", "もつ", "motsu", "to hold"],
    ["置く", "おく", "oku", "to place"],
    ["住む", "すむ", "sumu", "to live"],
    ["休む", "やすむ", "yasumu", "to rest"],
    ["遊ぶ", "あそぶ", "asobu", "to play"],
    ["歌う", "うたう", "utau", "to sing"],
    ["返す", "かえす", "kaesu", "to return something"],
  ]),
  createLesson(17, "形", "Adjectives I", [
    ["大きい", "おおきい", "ookii", "big"],
    ["小さい", "ちいさい", "chiisai", "small"],
    ["長い", "ながい", "nagai", "long"],
    ["短い", "みじかい", "mijikai", "short"],
    ["多い", "おおい", "ooi", "many"],
    ["少ない", "すくない", "sukunai", "few"],
    ["早い", "はやい", "hayai", "early / fast"],
    ["遅い", "おそい", "osoi", "late / slow"],
    ["明るい", "あかるい", "akarui", "bright"],
    ["暗い", "くらい", "kurai", "dark"],
    ["強い", "つよい", "tsuyoi", "strong"],
    ["弱い", "よわい", "yowai", "weak"],
    ["軽い", "かるい", "karui", "light in weight"],
    ["重い", "おもい", "omoi", "heavy"],
    ["良い", "いい", "ii", "good"],
    ["悪い", "わるい", "warui", "bad"],
    ["忙しい", "いそがしい", "isogashii", "busy"],
    ["暇", "ひま", "hima", "free / not busy"],
    ["面白い", "おもしろい", "omoshiroi", "interesting"],
    ["つまらない", "つまらない", "tsumaranai", "boring"],
  ]),
  createLesson(18, "心", "Adjectives II & Feelings", [
    ["うれしい", "うれしい", "ureshii", "happy"],
    ["悲しい", "かなしい", "kanashii", "sad"],
    ["楽しい", "たのしい", "tanoshii", "fun"],
    ["怖い", "こわい", "kowai", "scary"],
    ["寂しい", "さびしい", "sabishii", "lonely"],
    ["優しい", "やさしい", "yasashii", "kind / gentle"],
    ["親切", "しんせつ", "shinsetsu", "kindness / helpful"],
    ["有名", "ゆうめい", "yuumei", "famous"],
    ["静か", "しずか", "shizuka", "quiet"],
    ["にぎやか", "にぎやか", "nigiyaka", "lively"],
    ["きれい", "きれい", "kirei", "beautiful / clean"],
    ["便利", "べんり", "benri", "convenient"],
    ["不便", "ふべん", "fuben", "inconvenient"],
    ["好き", "すき", "suki", "liked / favorite"],
    ["嫌い", "きらい", "kirai", "disliked"],
    ["上手", "じょうず", "jouzu", "skillful"],
    ["下手", "へた", "heta", "unskilled"],
    ["大切", "たいせつ", "taisetsu", "important / precious"],
    ["同じ", "おなじ", "onaji", "same"],
    ["特別", "とくべつ", "tokubetsu", "special"],
  ]),
  createLesson(19, "色", "Colors & Shapes", [
    ["赤", "あか", "aka", "red"],
    ["青", "あお", "ao", "blue"],
    ["白", "しろ", "shiro", "white"],
    ["黒", "くろ", "kuro", "black"],
    ["黄色", "きいろ", "kiiro", "yellow"],
    ["緑", "みどり", "midori", "green"],
    ["茶色", "ちゃいろ", "chairo", "brown"],
    ["色", "いろ", "iro", "color"],
    ["丸", "まる", "maru", "circle"],
    ["四角", "しかく", "shikaku", "square"],
    ["三角", "さんかく", "sankaku", "triangle"],
    ["形", "かたち", "katachi", "shape"],
    ["長方形", "ちょうほうけい", "chouhoukei", "rectangle"],
    ["薄い", "うすい", "usui", "light / thin"],
    ["濃い", "こい", "koi", "dark / strong"],
    ["金色", "きんいろ", "kiniro", "gold color"],
    ["銀色", "ぎんいろ", "giniro", "silver color"],
    ["紫", "むらさき", "murasaki", "purple"],
    ["桃色", "ももいろ", "momoiro", "pink"],
    ["橙色", "だいだいいろ", "daidaiiro", "orange color"],
  ]),
  createLesson(20, "楽", "Hobbies & Leisure", [
    ["音楽", "おんがく", "ongaku", "music"],
    ["映画", "えいが", "eiga", "movie"],
    ["読書", "どくしょ", "dokusho", "reading books"],
    ["写真", "しゃしん", "shashin", "photograph"],
    ["旅行", "りょこう", "ryokou", "travel"],
    ["散歩", "さんぽ", "sanpo", "walk / stroll"],
    ["スポーツ", "すぽーつ", "supootsu", "sports"],
    ["サッカー", "さっかー", "sakkaa", "soccer"],
    ["野球", "やきゅう", "yakyuu", "baseball"],
    ["テニス", "てにす", "tenisu", "tennis"],
    ["泳ぐ", "およぐ", "oyogu", "to swim"],
    ["ダンス", "だんす", "dansu", "dance"],
    ["歌", "うた", "uta", "song"],
    ["絵", "え", "e", "picture"],
    ["ゲーム", "げーむ", "geemu", "game"],
    ["テレビ", "てれび", "terebi", "television"],
    ["ラジオ", "らじお", "rajio", "radio"],
    ["インターネット", "いんたーねっと", "intaanetto", "internet"],
    ["週末", "しゅうまつ", "shuumatsu", "weekend"],
    ["趣味", "しゅみ", "shumi", "hobby"],
  ]),
  createLesson(21, "犬", "Animals", [
    ["犬", "いぬ", "inu", "dog"],
    ["猫", "ねこ", "neko", "cat"],
    ["鳥", "とり", "tori", "bird"],
    ["魚", "さかな", "sakana", "fish"],
    ["馬", "うま", "uma", "horse"],
    ["牛", "うし", "ushi", "cow"],
    ["豚", "ぶた", "buta", "pig"],
    ["うさぎ", "うさぎ", "usagi", "rabbit"],
    ["猿", "さる", "saru", "monkey"],
    ["虫", "むし", "mushi", "insect"],
    ["動物", "どうぶつ", "doubutsu", "animal"],
    ["動物園", "どうぶつえん", "doubutsuen", "zoo"],
    ["山羊", "やぎ", "yagi", "goat"],
    ["羊", "ひつじ", "hitsuji", "sheep"],
    ["鶏", "にわとり", "niwatori", "chicken"],
    ["象", "ぞう", "zou", "elephant"],
    ["虎", "とら", "tora", "tiger"],
    ["熊", "くま", "kuma", "bear"],
    ["鹿", "しか", "shika", "deer"],
    ["狼", "おおかみ", "ookami", "wolf"],
  ]),
  createLesson(22, "旅", "Travel & Hotel", [
    ["旅行", "りょこう", "ryokou", "trip"],
    ["予約", "よやく", "yoyaku", "reservation"],
    ["荷物", "にもつ", "nimotsu", "luggage"],
    ["かばん", "かばん", "kaban", "bag"],
    ["旅館", "りょかん", "ryokan", "Japanese inn"],
    ["観光", "かんこう", "kankou", "sightseeing"],
    ["案内", "あんない", "annai", "guidance"],
    ["地下鉄", "ちかてつ", "chikatetsu", "subway"],
    ["パスポート", "ぱすぽーと", "pasupooto", "passport"],
    ["出発", "しゅっぱつ", "shuppatsu", "departure"],
    ["到着", "とうちゃく", "touchaku", "arrival"],
    ["遅れる", "おくれる", "okureru", "to be late"],
    ["泊まる", "とまる", "tomaru", "to stay overnight"],
    ["返す", "かえす", "kaesu", "to return something"],
    ["道案内", "みちあんない", "michiannai", "directions"],
    ["お土産", "おみやげ", "omiyage", "souvenir"],
    ["外国", "がいこく", "gaikoku", "foreign country"],
    ["窓口", "まどぐち", "madoguchi", "ticket window"],
    ["入場料", "にゅうじょうりょう", "nyuujouryou", "admission fee"],
    ["出張", "しゅっちょう", "shucchou", "business trip"],
  ]),
  createLesson(23, "文", "Everyday Expressions", [
    ["これ", "これ", "kore", "this"],
    ["それ", "それ", "sore", "that"],
    ["あれ", "あれ", "are", "that over there"],
    ["どれ", "どれ", "dore", "which one"],
    ["ここ", "ここ", "koko", "here"],
    ["そこ", "そこ", "soko", "there"],
    ["あそこ", "あそこ", "asoko", "over there"],
    ["どこ", "どこ", "doko", "where"],
    ["いつ", "いつ", "itsu", "when"],
    ["なぜ", "なぜ", "naze", "why"],
    ["どうして", "どうして", "doushite", "why / how come"],
    ["どうぞ", "どうぞ", "douzo", "please / go ahead"],
    ["まだ", "まだ", "mada", "still / not yet"],
    ["もう", "もう", "mou", "already / more"],
    ["いつも", "いつも", "itsumo", "always"],
    ["ときどき", "ときどき", "tokidoki", "sometimes"],
    ["たくさん", "たくさん", "takusan", "a lot"],
    ["少し", "すこし", "sukoshi", "a little"],
    ["本当に", "ほんとうに", "hontou ni", "really"],
    ["多分", "たぶん", "tabun", "probably"],
  ]),
  createLesson(24, "朝", "Daily Routine Phrases", [
    ["起きます", "おきます", "okimasu", "wake up"],
    ["顔を洗います", "かおをあらいます", "kao o araimasu", "wash my face"],
    ["歯を磨きます", "はをみがきます", "ha o migakimasu", "brush my teeth"],
    ["朝ご飯を食べます", "あさごはんをたべます", "asagohan o tabemasu", "eat breakfast"],
    ["学校へ行きます", "がっこうへいきます", "gakkou e ikimasu", "go to school"],
    ["仕事をします", "しごとをします", "shigoto o shimasu", "do work"],
    ["昼ご飯を食べます", "ひるごはんをたべます", "hirugohan o tabemasu", "eat lunch"],
    ["勉強します", "べんきょうします", "benkyou shimasu", "study"],
    ["家に帰ります", "いえにかえります", "ie ni kaerimasu", "go home"],
    ["晩ご飯を作ります", "ばんごはんをつくります", "bangohan o tsukurimasu", "make dinner"],
    ["晩ご飯を食べます", "ばんごはんをたべます", "bangohan o tabemasu", "eat dinner"],
    ["テレビを見ます", "てれびをみます", "terebi o mimasu", "watch TV"],
    ["音楽を聞きます", "おんがくをききます", "ongaku o kikimasu", "listen to music"],
    ["お風呂に入ります", "おふろにはいります", "ofuro ni hairimasu", "take a bath"],
    ["本を読みます", "ほんをよみます", "hon o yomimasu", "read a book"],
    ["宿題をします", "しゅくだいをします", "shukudai o shimasu", "do homework"],
    ["友達に会います", "ともだちにあいます", "tomodachi ni aimasu", "meet a friend"],
    ["買い物をします", "かいものをします", "kaimono o shimasu", "go shopping"],
    ["寝ます", "ねます", "nemasu", "go to sleep"],
    ["休みます", "やすみます", "yasumimasu", "rest"],
  ]),
  createLesson(25, "位", "Position & Frequency", [
    ["前", "まえ", "mae", "front / before"],
    ["後ろ", "うしろ", "ushiro", "back / behind"],
    ["上", "うえ", "ue", "up / above"],
    ["下", "した", "shita", "down / below"],
    ["中", "なか", "naka", "inside"],
    ["外", "そと", "soto", "outside"],
    ["後", "あと", "ato", "after / later"],
    ["隣", "となり", "tonari", "next to"],
    ["近い", "ちかい", "chikai", "near"],
    ["遠い", "とおい", "tooi", "far"],
    ["一緒", "いっしょ", "issho", "together"],
    ["別", "べつ", "betsu", "separate / different"],
    ["次", "つぎ", "tsugi", "next"],
    ["毎週", "まいしゅう", "maishuu", "every week"],
    ["毎月", "まいつき", "maitsuki", "every month"],
    ["毎年", "まいとし", "maitoshi", "every year"],
    ["今年", "ことし", "kotoshi", "this year"],
    ["去年", "きょねん", "kyonen", "last year"],
    ["来年", "らいねん", "rainen", "next year"],
    ["初めて", "はじめて", "hajimete", "for the first time"],
  ]),
];

export const totalVocabularyWords = vocabularyLessons.reduce(
  (total, lesson) => total + lesson.chars.length,
  0
);

export function getDailyVocabularyLesson(date = new Date()) {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date - start;
  const dayOfYear = Math.floor(diff / 86400000);
  return vocabularyLessons[(dayOfYear - 1) % vocabularyLessons.length];
}